// Angular/src/app/orig_app.component.ts
import { Component, ViewChild } from '@angular/core';
import { DxHtmlEditorComponent } from "devextreme-angular/ui/html-editor";
import { replaceVariables } from "./replace-variables";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  @ViewChild("editor", { static: false }) htmlEditor!: DxHtmlEditorComponent;

  title = 'Angular';
  initialValue: string = `<p>This is a demo to illustrate how to parse and convert variables. To get started, input several variables into the editor, type the variable's values in the TextBoxes below, and click the "Convert HtmlEditor variables" button.</p>`;
  firstName: string = "";
  lastName: string = "";

  convertVariableOnClick() {
    const firstName = (this.firstName.length > 0) ? this.firstName : "John";
    const lastName = (this.lastName.length > 0) ? this.lastName : "Smith";
    let value: string = this.htmlEditor?.instance.option("value");
    
    value = replaceVariables(value,
      {
        "FirstName": firstName,
        "LastName": lastName
      }
    );

    this.htmlEditor?.instance.option("value", value);
  }

  constructor() {
    this.convertVariableOnClick = this.convertVariableOnClick.bind(this);
  }
}
<div class="default-style">
  <dx-html-editor #editor [value]="initialValue" [height]="400">
    <dxo-toolbar [multiline]="true">
      <dxi-item name="undo"></dxi-item>
      <dxi-item name="redo"></dxi-item>
      <dxi-item name="separator"></dxi-item>
      <dxi-item name="variable"></dxi-item>
      <dxi-item name="separator"></dxi-item>
      <dxi-item name="bold"></dxi-item>
      <dxi-item name="italic"></dxi-item>
      <dxi-item name="strike"></dxi-item>
      <dxi-item name="underline"></dxi-item>
      <dxi-item name="separator"></dxi-item>
      <dxi-item widget="dxButton"
        [options]="{ text: 'Convert HtmlEditor variables', onClick: convertVariableOnClick }"></dxi-item>
    </dxo-toolbar>
    <dxo-variables [dataSource]="[ 'FirstName', 'LastName' ]" [escapeChar]="[ '{', '}' ]">
    </dxo-variables>
  </dx-html-editor>
  <dx-text-box [(value)]="firstName" label="FirstName - Default: 'John'" labelMode="floating"></dx-text-box>
  <dx-text-box [(value)]="lastName" label="LastName - Default: 'John'" labelMode="floating"></dx-text-box>
</div>

// React/src/orig_App.tsx
import React, {
  useCallback,
  useMemo,
  useState,
  useRef,
  useLayoutEffect,
  MutableRefObject
} from "react";

import HtmlEditor, {
  Toolbar,
  Item,
  Variables
} from "devextreme-react/html-editor";
import { ButtonTypes } from "devextreme-react/button";
import TextBox from "devextreme-react/text-box";
import { ValueChangedEvent as TextValueChanged } from "devextreme/ui/text_box";
import { ValueChangedEvent as HtmlValueChanged } from "devextreme/ui/html_editor";
import markup, { Name } from "./data";

function useEvent(handler: () => void) {
  const handlerRef: MutableRefObject<any> = useRef(null);

  useLayoutEffect(() => {
    handlerRef.current = handler;
  });

  return useCallback((...args: []) => {
    const fn: () => void = handlerRef.current;
    return fn(...args);
  }, []);
}

const DX_VARIABLE_CLASS: string = "dx-variable";
const DATA_VAR_VALUE_ATTR: string = "data-var-value";

const variables: Array<string> = ["FirstName", "LastName"];
const escapeCharacters: Array<string> = ["{", "}"];

const replaceVariables = (value: string, variablesMap: Name): string => {
  const parser: DOMParser = new DOMParser();

  const doc: Document = parser.parseFromString(value, "text/html");
  const variables: NodeListOf<Element> = doc.querySelectorAll(
    `.${DX_VARIABLE_CLASS}`
  );

  variables.forEach((variable: Element): void => {
    const variableValue: string =
      variablesMap[variable.getAttribute(DATA_VAR_VALUE_ATTR)];
    variable.outerHTML = variableValue;
  });

  return doc.body.innerHTML.toString();
};

function App(): React.ReactElement {
  const [value, setValue] = useState(markup);
  const [firstNameTextBoxValue, setFirstNameTextBoxValue] = useState("John");
  const [lastNameTextBoxValue, setLastNameTextBoxValue] = useState("Smith");

  const convertVariableOnClick = useEvent((): void => {
    const valueWithReplacedVariables = replaceVariables(value, {
      FirstName: firstNameTextBoxValue,
      LastName: lastNameTextBoxValue
    });

    setValue(valueWithReplacedVariables);
  });

  const htmlEditorOnValueChanged = useCallback((e: HtmlValueChanged): void => {
    setValue(e.value);
  }, []);

  const textBoxOnValueChanged = useCallback((e: TextValueChanged): void => {
    if (e.element.id === "first-name") {
      setFirstNameTextBoxValue(e.value);
    } else if (e.element.id === "last-name") {
      setLastNameTextBoxValue(e.value);
    }
  }, []);

  const toolbarButtonOptions: ButtonTypes.Properties = useMemo(
    () => ({
      text: "Convert HtmlEditor variables",
      onClick: convertVariableOnClick
    }),
    [convertVariableOnClick]
  );

  return (
    <div className="widget-container">
      <HtmlEditor
        value={value}
        onValueChanged={htmlEditorOnValueChanged}
        height={400}
      >
        <Toolbar multiline={true}>
          <Item name="undo" />
          <Item name="redo" />
          <Item name="separator" />
          <Item name="variable" />
          <Item name="separator" />
          <Item name="bold" />
          <Item name="italic" />
          <Item name="strike" />
          <Item name="underline" />
          <Item name="separator" />
          <Item widget="dxButton" options={toolbarButtonOptions} />
        </Toolbar>

        <Variables dataSource={variables} escapeChar={escapeCharacters} />
      </HtmlEditor>

      <TextBox
        id="first-name"
        value={firstNameTextBoxValue}
        label="FirstName"
        labelMode="floating"
        onValueChanged={textBoxOnValueChanged}
      />
      <TextBox
        id="last-name"
        value={lastNameTextBoxValue}
        label="LastName"
        labelMode="floating"
        onValueChanged={textBoxOnValueChanged}
      />
    </div>
  );
}

export default App;
